### ISSUE TITLE
[Bug] Can't get it to show up.

### ISSUE THREAD

**Issue by jan-happy** [f-meloni/EasyToast#1]
Neither .top nor .bottom position shows up.
Tried with iOS 10.1 and 10.2.
Mabye it is because I'm using a TabbarController?

**Comment by f-meloni** [comment]
EasyToast creates creates a new `UIWindow` to show toasts, then you TabBarController should not be a problem anyway i'm going to try to reproduce the problem.

Can you give me an example that can help me to reproduce the problem, please?

**Comment by jan-happy** [comment]
Sure! This is just a plain TabBar Project. The Toast ist not displayed in the simulator...
[TestToast.zip](https://github.com/f-meloni/EasyToast/files/648445/TestToast.zip)

**Comment by f-meloni** [comment]
Ok,
I found the problem... 
I will make a new version of the pod

**Comment by f-meloni** [comment]
Try version 2.0.2 👍 
Please let me know if it resolved your problem

**Comment by jan-happy** [comment]
Wow, works like a charm! Thank you!
I used ASToast in the meantime but will go back to EasyToast since it's much more nicely animated and configurable ;)

**Comment by f-meloni** [comment]
Perfect,
Thank you :)
